[package]
name = "blockchain_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
common = { path = "../common" }
parking_lot = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
proto_gen = { path = "../proto_gen" }
