[project]
name = "minchash"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "marimo>=0.8.22",
    "matplotlib>=3.7.5",
    "seaborn>=0.13.2",
]

[dependency-groups]
dev = [
    "types-seaborn>=0.13.2.20250914",
]

[tool.ruff]
exclude = ["result/plot.py"]